# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sleep\OneDrive\Documents\shotgun\mastertemplate\install\manual\tk-blaster\v0.0.2\python\blaster\ui\blaster_ui.ui'
#
# Created: Wed Aug 01 23:50:27 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from sgtk.platform.qt import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(818, 894)
        Form.setMinimumSize(QtCore.QSize(604, 0))
        Form.setStyleSheet("background-color: rgb(75, 75, 75);\n"
"color: rgb(229, 229, 229);")
        self.verticalLayout_8 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Logo = QtGui.QLabel(Form)
        self.Logo.setMinimumSize(QtCore.QSize(100, 50))
        self.Logo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Logo.setStyleSheet("image: url(:/logos/blaster.png);\n"
"image-align: \'left\';")
        self.Logo.setText("")
        self.Logo.setScaledContents(False)
        self.Logo.setObjectName("Logo")
        self.horizontalLayout_9.addWidget(self.Logo)
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.Blaster_Options_Pages = QtGui.QToolBox(Form)
        self.Blaster_Options_Pages.setMinimumSize(QtCore.QSize(0, 651))
        self.Blaster_Options_Pages.setStyleSheet("background-color: rgb(75, 75, 75);\n"
"color: rgb(229, 229, 229);")
        self.Blaster_Options_Pages.setObjectName("Blaster_Options_Pages")
        self.playblast = QtGui.QWidget()
        self.playblast.setGeometry(QtCore.QRect(0, 0, 792, 690))
        self.playblast.setObjectName("playblast")
        self.viewport_group = QtGui.QGroupBox(self.playblast)
        self.viewport_group.setGeometry(QtCore.QRect(450, 10, 341, 261))
        self.viewport_group.setMinimumSize(QtCore.QSize(231, 261))
        self.viewport_group.setObjectName("viewport_group")
        self.layoutWidget = QtGui.QWidget(self.viewport_group)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 194, 197))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.show_ornaments = QtGui.QCheckBox(self.layoutWidget)
        self.show_ornaments.setStyleSheet("")
        self.show_ornaments.setObjectName("show_ornaments")
        self.verticalLayout.addWidget(self.show_ornaments)
        self.backface_culling = QtGui.QCheckBox(self.layoutWidget)
        self.backface_culling.setStyleSheet("")
        self.backface_culling.setObjectName("backface_culling")
        self.verticalLayout.addWidget(self.backface_culling)
        self.image_planes = QtGui.QCheckBox(self.layoutWidget)
        self.image_planes.setStyleSheet("")
        self.image_planes.setObjectName("image_planes")
        self.verticalLayout.addWidget(self.image_planes)
        self.two_sided_lighting = QtGui.QCheckBox(self.layoutWidget)
        self.two_sided_lighting.setStyleSheet("")
        self.two_sided_lighting.setChecked(True)
        self.two_sided_lighting.setObjectName("two_sided_lighting")
        self.verticalLayout.addWidget(self.two_sided_lighting)
        self.match_render_output = QtGui.QCheckBox(self.layoutWidget)
        self.match_render_output.setChecked(True)
        self.match_render_output.setObjectName("match_render_output")
        self.verticalLayout.addWidget(self.match_render_output)
        self.default_material = QtGui.QCheckBox(self.layoutWidget)
        self.default_material.setObjectName("default_material")
        self.verticalLayout.addWidget(self.default_material)
        self.shotgun_connection = QtGui.QGroupBox(self.playblast)
        self.shotgun_connection.setGeometry(QtCore.QRect(10, 400, 421, 281))
        self.shotgun_connection.setMinimumSize(QtCore.QSize(421, 281))
        self.shotgun_connection.setCheckable(True)
        self.shotgun_connection.setObjectName("shotgun_connection")
        self.current_context_grp = QtGui.QGroupBox(self.shotgun_connection)
        self.current_context_grp.setGeometry(QtCore.QRect(20, 40, 381, 131))
        self.current_context_grp.setMinimumSize(QtCore.QSize(381, 131))
        self.current_context_grp.setStyleSheet("border: none;\n"
"background-color: rgb(75, 75, 75);\n"
"color: rgb(229, 229, 229);")
        self.current_context_grp.setObjectName("current_context_grp")
        self.layoutWidget1 = QtGui.QWidget(self.current_context_grp)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 351, 105))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.employee_label = QtGui.QLabel(self.layoutWidget1)
        self.employee_label.setObjectName("employee_label")
        self.verticalLayout_6.addWidget(self.employee_label)
        self.project_label = QtGui.QLabel(self.layoutWidget1)
        self.project_label.setObjectName("project_label")
        self.verticalLayout_6.addWidget(self.project_label)
        self.asset_shot_label = QtGui.QLabel(self.layoutWidget1)
        self.asset_shot_label.setObjectName("asset_shot_label")
        self.verticalLayout_6.addWidget(self.asset_shot_label)
        self.task_label = QtGui.QLabel(self.layoutWidget1)
        self.task_label.setObjectName("task_label")
        self.verticalLayout_6.addWidget(self.task_label)
        self.publish_sg_version = QtGui.QCheckBox(self.shotgun_connection)
        self.publish_sg_version.setGeometry(QtCore.QRect(20, 180, 341, 25))
        self.publish_sg_version.setStyleSheet("background-color: rgb(75, 75, 75);\n"
"color: rgb(229, 229, 229);")
        self.publish_sg_version.setChecked(True)
        self.publish_sg_version.setObjectName("publish_sg_version")
        self.keep_in_pipeline = QtGui.QCheckBox(self.shotgun_connection)
        self.keep_in_pipeline.setGeometry(QtCore.QRect(20, 200, 321, 25))
        self.keep_in_pipeline.setStyleSheet("background-color: rgb(75, 75, 75);\n"
"color: rgb(229, 229, 229);")
        self.keep_in_pipeline.setChecked(True)
        self.keep_in_pipeline.setObjectName("keep_in_pipeline")
        self.layoutWidget2 = QtGui.QWidget(self.shotgun_connection)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 230, 381, 36))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.browse = QtGui.QLineEdit(self.layoutWidget2)
        self.browse.setStyleSheet("QLineEdit { color: rgb(229, 229, 229); border: none }\n"
"")
        self.browse.setObjectName("browse")
        self.horizontalLayout_7.addWidget(self.browse)
        self.browse_btn = QtGui.QPushButton(self.layoutWidget2)
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout_7.addWidget(self.browse_btn)
        self.beautify_grp = QtGui.QGroupBox(self.playblast)
        self.beautify_grp.setGeometry(QtCore.QRect(440, 290, 351, 151))
        self.beautify_grp.setMinimumSize(QtCore.QSize(351, 151))
        self.beautify_grp.setStyleSheet("background-color: rgb(75, 75, 75);\n"
"color: rgb(229, 229, 229);")
        self.beautify_grp.setObjectName("beautify_grp")
        self.layoutWidget3 = QtGui.QWidget(self.beautify_grp)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 331, 123))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.use_lights = QtGui.QCheckBox(self.layoutWidget3)
        self.use_lights.setChecked(True)
        self.use_lights.setObjectName("use_lights")
        self.verticalLayout_4.addWidget(self.use_lights)
        self.cast_shadows = QtGui.QCheckBox(self.layoutWidget3)
        self.cast_shadows.setChecked(True)
        self.cast_shadows.setObjectName("cast_shadows")
        self.verticalLayout_4.addWidget(self.cast_shadows)
        self.ambient_occlusion = QtGui.QCheckBox(self.layoutWidget3)
        self.ambient_occlusion.setChecked(True)
        self.ambient_occlusion.setObjectName("ambient_occlusion")
        self.verticalLayout_4.addWidget(self.ambient_occlusion)
        self.motion_blur = QtGui.QCheckBox(self.layoutWidget3)
        self.motion_blur.setChecked(True)
        self.motion_blur.setObjectName("motion_blur")
        self.verticalLayout_4.addWidget(self.motion_blur)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textured = QtGui.QCheckBox(self.layoutWidget3)
        self.textured.setChecked(True)
        self.textured.setObjectName("textured")
        self.verticalLayout_5.addWidget(self.textured)
        self.smooth_shading = QtGui.QCheckBox(self.layoutWidget3)
        self.smooth_shading.setChecked(True)
        self.smooth_shading.setObjectName("smooth_shading")
        self.verticalLayout_5.addWidget(self.smooth_shading)
        self.wireframe = QtGui.QCheckBox(self.layoutWidget3)
        self.wireframe.setObjectName("wireframe")
        self.verticalLayout_5.addWidget(self.wireframe)
        self.anti_aliasing = QtGui.QCheckBox(self.layoutWidget3)
        self.anti_aliasing.setChecked(True)
        self.anti_aliasing.setObjectName("anti_aliasing")
        self.verticalLayout_5.addWidget(self.anti_aliasing)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.main_engine_grp = QtGui.QGroupBox(self.playblast)
        self.main_engine_grp.setGeometry(QtCore.QRect(10, 10, 421, 371))
        self.main_engine_grp.setMinimumSize(QtCore.QSize(421, 371))
        self.main_engine_grp.setObjectName("main_engine_grp")
        self.layoutWidget4 = QtGui.QWidget(self.main_engine_grp)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 401, 321))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.render_power = QtGui.QGroupBox(self.layoutWidget4)
        self.render_power.setStyleSheet("border: none;\n"
"background-color: rgb(75, 75, 75);\n"
"color: rgb(229, 229, 229);")
        self.render_power.setObjectName("render_power")
        self.layoutWidget5 = QtGui.QWidget(self.render_power)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 30, 281, 23))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.farm = QtGui.QRadioButton(self.layoutWidget5)
        self.farm.setChecked(True)
        self.farm.setObjectName("farm")
        self.horizontalLayout_5.addWidget(self.farm)
        self.local = QtGui.QRadioButton(self.layoutWidget5)
        self.local.setObjectName("local")
        self.horizontalLayout_5.addWidget(self.local)
        self.verticalLayout_3.addWidget(self.render_power)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cameras_label = QtGui.QLabel(self.layoutWidget4)
        self.cameras_label.setObjectName("cameras_label")
        self.horizontalLayout_4.addWidget(self.cameras_label)
        self.cameras = QtGui.QComboBox(self.layoutWidget4)
        self.cameras.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.cameras.setDuplicatesEnabled(False)
        self.cameras.setObjectName("cameras")
        self.horizontalLayout_4.addWidget(self.cameras)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.render_formats_label = QtGui.QLabel(self.layoutWidget4)
        self.render_formats_label.setObjectName("render_formats_label")
        self.horizontalLayout_3.addWidget(self.render_formats_label)
        self.render_formats = QtGui.QComboBox(self.layoutWidget4)
        self.render_formats.setObjectName("render_formats")
        self.render_formats.addItem("")
        self.render_formats.addItem("")
        self.render_formats.addItem("")
        self.render_formats.addItem("")
        self.horizontalLayout_3.addWidget(self.render_formats)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.encoding_label = QtGui.QLabel(self.layoutWidget4)
        self.encoding_label.setMinimumSize(QtCore.QSize(150, 0))
        self.encoding_label.setObjectName("encoding_label")
        self.horizontalLayout_10.addWidget(self.encoding_label)
        self.encoding = QtGui.QComboBox(self.layoutWidget4)
        self.encoding.setObjectName("encoding")
        self.encoding.addItem("")
        self.encoding.addItem("")
        self.encoding.addItem("")
        self.horizontalLayout_10.addWidget(self.encoding)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.quality_label_2 = QtGui.QLabel(self.layoutWidget4)
        self.quality_label_2.setObjectName("quality_label_2")
        self.horizontalLayout_12.addWidget(self.quality_label_2)
        self.quality_slider = QtGui.QSlider(self.layoutWidget4)
        self.quality_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #4b4b4b, stop: 1 #fff);\n"
"background: qlineargradient(x1: 0, y1:0.25, x2: 1, y2: 1.25,\n"
"    stop: 0 #4b4b4b, stop: 1 #fff);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #4b4b4b, stop:1 #e5e5e5);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #f60);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.quality_slider.setMinimum(1)
        self.quality_slider.setMaximum(10)
        self.quality_slider.setProperty("value", 7)
        self.quality_slider.setOrientation(QtCore.Qt.Horizontal)
        self.quality_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.quality_slider.setObjectName("quality_slider")
        self.horizontalLayout_12.addWidget(self.quality_slider)
        self.quality_value_2 = QtGui.QSpinBox(self.layoutWidget4)
        self.quality_value_2.setMinimum(1)
        self.quality_value_2.setMaximum(10)
        self.quality_value_2.setProperty("value", 7)
        self.quality_value_2.setObjectName("quality_value_2")
        self.horizontalLayout_12.addWidget(self.quality_value_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scale_label = QtGui.QLabel(self.layoutWidget4)
        self.scale_label.setObjectName("scale_label")
        self.horizontalLayout_2.addWidget(self.scale_label)
        self.scale = QtGui.QComboBox(self.layoutWidget4)
        self.scale.setObjectName("scale")
        self.scale.addItem("")
        self.scale.addItem("")
        self.scale.addItem("")
        self.scale.addItem("")
        self.scale.addItem("")
        self.scale.addItem("")
        self.scale.addItem("")
        self.scale.addItem("")
        self.scale.addItem("")
        self.scale.addItem("")
        self.horizontalLayout_2.addWidget(self.scale)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.groupBox_6 = QtGui.QGroupBox(self.layoutWidget4)
        self.groupBox_6.setStyleSheet("border: none;\n"
"background-color: rgb(75, 75, 75);\n"
"color: rgb(229, 229, 229);")
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget6 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 30, 281, 25))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_frame = QtGui.QSpinBox(self.layoutWidget6)
        self.start_frame.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.start_frame.setObjectName("start_frame")
        self.horizontalLayout.addWidget(self.start_frame)
        self.end_frame = QtGui.QSpinBox(self.layoutWidget6)
        self.end_frame.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.end_frame.setObjectName("end_frame")
        self.horizontalLayout.addWidget(self.end_frame)
        self.sg_sync_btn = QtGui.QPushButton(self.layoutWidget6)
        self.sg_sync_btn.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.sg_sync_btn.setObjectName("sg_sync_btn")
        self.horizontalLayout.addWidget(self.sg_sync_btn)
        self.time_snyc_btn = QtGui.QPushButton(self.layoutWidget6)
        self.time_snyc_btn.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.time_snyc_btn.setObjectName("time_snyc_btn")
        self.horizontalLayout.addWidget(self.time_snyc_btn)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.preview = QtGui.QGraphicsView(self.playblast)
        self.preview.setGeometry(QtCore.QRect(440, 450, 351, 231))
        self.preview.setObjectName("preview")
        self.Blaster_Options_Pages.addItem(self.playblast, "")
        self.deadline = QtGui.QWidget()
        self.deadline.setGeometry(QtCore.QRect(0, 0, 792, 690))
        self.deadline.setObjectName("deadline")
        self.layoutWidget7 = QtGui.QWidget(self.deadline)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 15, 541, 366))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.job_name_label = QtGui.QLabel(self.layoutWidget7)
        self.job_name_label.setMinimumSize(QtCore.QSize(100, 0))
        self.job_name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.job_name_label.setObjectName("job_name_label")
        self.horizontalLayout_19.addWidget(self.job_name_label)
        self.job_name = QtGui.QLineEdit(self.layoutWidget7)
        self.job_name.setObjectName("job_name")
        self.horizontalLayout_19.addWidget(self.job_name)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.user_label = QtGui.QLabel(self.layoutWidget7)
        self.user_label.setMinimumSize(QtCore.QSize(100, 0))
        self.user_label.setObjectName("user_label")
        self.horizontalLayout_18.addWidget(self.user_label)
        self.user = QtGui.QLineEdit(self.layoutWidget7)
        self.user.setEnabled(False)
        self.user.setObjectName("user")
        self.horizontalLayout_18.addWidget(self.user)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.priority_label = QtGui.QLabel(self.layoutWidget7)
        self.priority_label.setMinimumSize(QtCore.QSize(100, 0))
        self.priority_label.setObjectName("priority_label")
        self.horizontalLayout_17.addWidget(self.priority_label)
        self.priority = QtGui.QLineEdit(self.layoutWidget7)
        self.priority.setMaximumSize(QtCore.QSize(50, 16777215))
        self.priority.setObjectName("priority")
        self.horizontalLayout_17.addWidget(self.priority)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pool_label = QtGui.QLabel(self.layoutWidget7)
        self.pool_label.setMinimumSize(QtCore.QSize(100, 0))
        self.pool_label.setObjectName("pool_label")
        self.horizontalLayout_20.addWidget(self.pool_label)
        self.pool = QtGui.QComboBox(self.layoutWidget7)
        self.pool.setObjectName("pool")
        self.horizontalLayout_20.addWidget(self.pool)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.machine_list_label = QtGui.QLabel(self.layoutWidget7)
        self.machine_list_label.setMinimumSize(QtCore.QSize(100, 0))
        self.machine_list_label.setObjectName("machine_list_label")
        self.horizontalLayout_21.addWidget(self.machine_list_label)
        self.machine_list = QtGui.QLineEdit(self.layoutWidget7)
        self.machine_list.setObjectName("machine_list")
        self.horizontalLayout_21.addWidget(self.machine_list)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frames_per_machine_label = QtGui.QLabel(self.layoutWidget7)
        self.frames_per_machine_label.setObjectName("frames_per_machine_label")
        self.horizontalLayout_16.addWidget(self.frames_per_machine_label)
        self.frames_per_machine = QtGui.QLineEdit(self.layoutWidget7)
        self.frames_per_machine.setEnabled(False)
        self.frames_per_machine.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frames_per_machine.setObjectName("frames_per_machine")
        self.horizontalLayout_16.addWidget(self.frames_per_machine)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.blacklist = QtGui.QCheckBox(self.layoutWidget7)
        self.blacklist.setChecked(True)
        self.blacklist.setObjectName("blacklist")
        self.verticalLayout_7.addWidget(self.blacklist)
        self.Blaster_Options_Pages.addItem(self.deadline, "")
        self.verticalLayout_8.addWidget(self.Blaster_Options_Pages)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.cancel_btn = QtGui.QPushButton(Form)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_8.addWidget(self.cancel_btn)
        self.blaster_btn = QtGui.QPushButton(Form)
        self.blaster_btn.setObjectName("blaster_btn")
        self.horizontalLayout_8.addWidget(self.blaster_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.cameras_label.setBuddy(self.cameras)
        self.render_formats_label.setBuddy(self.render_formats)
        self.encoding_label.setBuddy(self.encoding)
        self.quality_label_2.setBuddy(self.quality_slider)
        self.scale_label.setBuddy(self.scale)
        self.user_label.setBuddy(self.user)
        self.priority_label.setBuddy(self.priority)
        self.pool_label.setBuddy(self.pool)
        self.machine_list_label.setBuddy(self.machine_list)
        self.frames_per_machine_label.setBuddy(self.frames_per_machine)

        self.retranslateUi(Form)
        self.Blaster_Options_Pages.setCurrentIndex(0)
        self.scale.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.blaster_btn, self.cancel_btn)
        Form.setTabOrder(self.cancel_btn, self.farm)
        Form.setTabOrder(self.farm, self.local)
        Form.setTabOrder(self.local, self.cameras)
        Form.setTabOrder(self.cameras, self.render_formats)
        Form.setTabOrder(self.render_formats, self.encoding)
        Form.setTabOrder(self.encoding, self.scale)
        Form.setTabOrder(self.scale, self.sg_sync_btn)
        Form.setTabOrder(self.sg_sync_btn, self.time_snyc_btn)
        Form.setTabOrder(self.time_snyc_btn, self.publish_sg_version)
        Form.setTabOrder(self.publish_sg_version, self.keep_in_pipeline)
        Form.setTabOrder(self.keep_in_pipeline, self.browse)
        Form.setTabOrder(self.browse, self.browse_btn)
        Form.setTabOrder(self.browse_btn, self.show_ornaments)
        Form.setTabOrder(self.show_ornaments, self.backface_culling)
        Form.setTabOrder(self.backface_culling, self.image_planes)
        Form.setTabOrder(self.image_planes, self.two_sided_lighting)
        Form.setTabOrder(self.two_sided_lighting, self.match_render_output)
        Form.setTabOrder(self.match_render_output, self.default_material)
        Form.setTabOrder(self.default_material, self.use_lights)
        Form.setTabOrder(self.use_lights, self.textured)
        Form.setTabOrder(self.textured, self.cast_shadows)
        Form.setTabOrder(self.cast_shadows, self.smooth_shading)
        Form.setTabOrder(self.smooth_shading, self.ambient_occlusion)
        Form.setTabOrder(self.ambient_occlusion, self.wireframe)
        Form.setTabOrder(self.wireframe, self.motion_blur)
        Form.setTabOrder(self.motion_blur, self.anti_aliasing)
        Form.setTabOrder(self.anti_aliasing, self.shotgun_connection)
        Form.setTabOrder(self.shotgun_connection, self.start_frame)
        Form.setTabOrder(self.start_frame, self.end_frame)
        Form.setTabOrder(self.end_frame, self.job_name)
        Form.setTabOrder(self.job_name, self.user)
        Form.setTabOrder(self.user, self.priority)
        Form.setTabOrder(self.priority, self.pool)
        Form.setTabOrder(self.pool, self.machine_list)
        Form.setTabOrder(self.machine_list, self.frames_per_machine)
        Form.setTabOrder(self.frames_per_machine, self.blacklist)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None))
        self.viewport_group.setTitle(QtGui.QApplication.translate("Form", "Viewport Options", None))
        self.show_ornaments.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Window Ornaments include heads-up displays, like poly count, or focal length, frame borders like the film gate, title safe/action safe.</p></body></html>", None))
        self.show_ornaments.setText(QtGui.QApplication.translate("Form", "Show Ornaments", None))
        self.backface_culling.setText(QtGui.QApplication.translate("Form", "Backface Culling", None))
        self.image_planes.setText(QtGui.QApplication.translate("Form", "Show Image Planes", None))
        self.two_sided_lighting.setText(QtGui.QApplication.translate("Form", "Two Sided Lighting", None))
        self.match_render_output.setText(QtGui.QApplication.translate("Form", "Match Render Output", None))
        self.default_material.setText(QtGui.QApplication.translate("Form", "Default Material", None))
        self.shotgun_connection.setTitle(QtGui.QApplication.translate("Form", "Shotgun Connection", None))
        self.current_context_grp.setTitle(QtGui.QApplication.translate("Form", "Current Context", None))
        self.employee_label.setText(QtGui.QApplication.translate("Form", "Employee", None))
        self.project_label.setText(QtGui.QApplication.translate("Form", "Project", None))
        self.asset_shot_label.setText(QtGui.QApplication.translate("Form", "Asset - Shot", None))
        self.task_label.setText(QtGui.QApplication.translate("Form", "Task", None))
        self.publish_sg_version.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Publish to Shotgun will automatically create a version for the specific asset, shot or task.</p></body></html>", None))
        self.publish_sg_version.setText(QtGui.QApplication.translate("Form", "Pubish Shotgun Version (Recommended)", None))
        self.keep_in_pipeline.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Keep it in the pipeline is the recommended setting, because it will automatically put the playblast in the correct shot folder on the server, based on Shotgun\'s configuration.  Turning this feature off will require that you choose a folder to render the playblast to.</p></body></html>", None))
        self.keep_in_pipeline.setText(QtGui.QApplication.translate("Form", "Keep it in the pipeline (Recommended)", None))
        self.browse.setToolTip(QtGui.QApplication.translate("Form", "Where to save the playblast if it\'s not going to the correct folder on the server", None))
        self.browse.setPlaceholderText(QtGui.QApplication.translate("Form", "Non-Pipeline Save Location", None))
        self.browse_btn.setText(QtGui.QApplication.translate("Form", "Browse...", None))
        self.beautify_grp.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Enable Viewport beautifications like Motion Blur, AO, lights or others.</p></body></html>", None))
        self.beautify_grp.setTitle(QtGui.QApplication.translate("Form", "Beautify", None))
        self.use_lights.setText(QtGui.QApplication.translate("Form", "Use Lights", None))
        self.cast_shadows.setText(QtGui.QApplication.translate("Form", "Cast Shadows", None))
        self.ambient_occlusion.setText(QtGui.QApplication.translate("Form", "Ambient Occlusion", None))
        self.motion_blur.setText(QtGui.QApplication.translate("Form", "Motion Blur", None))
        self.textured.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>When checked, Hardware texturing is turned on and Default Material is turned off.  If unchecked, Default Material will be set, but Hardware Texturing will be left in whatever state it currently is in.</p></body></html>", None))
        self.textured.setText(QtGui.QApplication.translate("Form", "Textured", None))
        self.smooth_shading.setText(QtGui.QApplication.translate("Form", "Smooth Shading", None))
        self.wireframe.setText(QtGui.QApplication.translate("Form", "Wireframe", None))
        self.anti_aliasing.setText(QtGui.QApplication.translate("Form", "Anti-Aliasing", None))
        self.main_engine_grp.setTitle(QtGui.QApplication.translate("Form", "Main Engine", None))
        self.render_power.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Render Power decides whether your playblast will be done locally (which will slow down your machine), or on the farm, which (in cases of long playblast times) will speed up your playblast time considerably.</p></body></html>", None))
        self.render_power.setTitle(QtGui.QApplication.translate("Form", "Render Power", None))
        self.farm.setText(QtGui.QApplication.translate("Form", "Farm", None))
        self.local.setText(QtGui.QApplication.translate("Form", "Local", None))
        self.cameras_label.setText(QtGui.QApplication.translate("Form", "Cameras", None))
        self.cameras.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Choose the Camera to playblast </p></body></html>", None))
        self.render_formats_label.setText(QtGui.QApplication.translate("Form", "Render Formats", None))
        self.render_formats.setItemText(0, QtGui.QApplication.translate("Form", "jpg", None))
        self.render_formats.setItemText(1, QtGui.QApplication.translate("Form", "png", None))
        self.render_formats.setItemText(2, QtGui.QApplication.translate("Form", "tif", None))
        self.render_formats.setItemText(3, QtGui.QApplication.translate("Form", "mov", None))
        self.encoding_label.setText(QtGui.QApplication.translate("Form", "Encoding", None))
        self.encoding.setItemText(0, QtGui.QApplication.translate("Form", "h.264", None))
        self.encoding.setItemText(1, QtGui.QApplication.translate("Form", "MPEG-4", None))
        self.encoding.setItemText(2, QtGui.QApplication.translate("Form", "Animation", None))
        self.quality_label_2.setText(QtGui.QApplication.translate("Form", "Quality", None))
        self.quality_slider.setToolTip(QtGui.QApplication.translate("Form", "The quality setting for the renderer.  ", None))
        self.quality_slider.setStatusTip(QtGui.QApplication.translate("Form", "The quality setting for the renderer.  ", None))
        self.quality_slider.setWhatsThis(QtGui.QApplication.translate("Form", "The quality setting for the renderer.  ", None))
        self.quality_value_2.setToolTip(QtGui.QApplication.translate("Form", "The quality setting for the renderer.  ", None))
        self.quality_value_2.setStatusTip(QtGui.QApplication.translate("Form", "The quality setting for the renderer.  ", None))
        self.quality_value_2.setWhatsThis(QtGui.QApplication.translate("Form", "The quality setting for the renderer.  ", None))
        self.scale_label.setText(QtGui.QApplication.translate("Form", "Scale", None))
        self.scale.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Scale the output down</p></body></html>", None))
        self.scale.setItemText(0, QtGui.QApplication.translate("Form", "10%", None))
        self.scale.setItemText(1, QtGui.QApplication.translate("Form", "25%", None))
        self.scale.setItemText(2, QtGui.QApplication.translate("Form", "50%", None))
        self.scale.setItemText(3, QtGui.QApplication.translate("Form", "75%", None))
        self.scale.setItemText(4, QtGui.QApplication.translate("Form", "100%", None))
        self.scale.setItemText(5, QtGui.QApplication.translate("Form", "110%", None))
        self.scale.setItemText(6, QtGui.QApplication.translate("Form", "130%", None))
        self.scale.setItemText(7, QtGui.QApplication.translate("Form", "150%", None))
        self.scale.setItemText(8, QtGui.QApplication.translate("Form", "175%", None))
        self.scale.setItemText(9, QtGui.QApplication.translate("Form", "200%", None))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "Time Frame", None))
        self.start_frame.setToolTip(QtGui.QApplication.translate("Form", "Start Frame", None))
        self.end_frame.setToolTip(QtGui.QApplication.translate("Form", "End Frame", None))
        self.sg_sync_btn.setToolTip(QtGui.QApplication.translate("Form", "Sync Frame Range to Shotgun", None))
        self.sg_sync_btn.setText(QtGui.QApplication.translate("Form", "SG Sync", None))
        self.time_snyc_btn.setToolTip(QtGui.QApplication.translate("Form", "Sync to Timeline", None))
        self.time_snyc_btn.setText(QtGui.QApplication.translate("Form", "Time Sync", None))
        self.Blaster_Options_Pages.setItemText(self.Blaster_Options_Pages.indexOf(self.playblast), QtGui.QApplication.translate("Form", "Blaster Options", None))
        self.job_name_label.setText(QtGui.QApplication.translate("Form", "Job Name", None))
        self.user_label.setText(QtGui.QApplication.translate("Form", "User", None))
        self.priority_label.setText(QtGui.QApplication.translate("Form", "Priority", None))
        self.priority.setText(QtGui.QApplication.translate("Form", "50", None))
        self.pool_label.setText(QtGui.QApplication.translate("Form", "Pool", None))
        self.machine_list_label.setText(QtGui.QApplication.translate("Form", "Machine List", None))
        self.frames_per_machine_label.setText(QtGui.QApplication.translate("Form", "frames per machine", None))
        self.frames_per_machine.setText(QtGui.QApplication.translate("Form", "10", None))
        self.blacklist.setText(QtGui.QApplication.translate("Form", "Machine List is a blacklist", None))
        self.Blaster_Options_Pages.setItemText(self.Blaster_Options_Pages.indexOf(self.deadline), QtGui.QApplication.translate("Form", "Deadline Options", None))
        self.cancel_btn.setText(QtGui.QApplication.translate("Form", "Cancel", None))
        self.blaster_btn.setText(QtGui.QApplication.translate("Form", "Blast It", None))

import resources_rc
